<?php
declare(strict_types=1);
?>
<div class="dg-legal-meta">
  <span class="dg-legal-meta-chip"><?= htmlspecialchars(t("legal.effective_date_label"), ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8") ?>: <?= htmlspecialchars(date("F j, Y"), ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8") ?></span>
</div>

<div class="dg-legal-prose">
<p class="dg-legal-intro">
  This Data Privacy Notice explains what personal data Drop Guard collects, why it is collected, how it is used,
  and the rights you have as a data subject. Drop Guard is an academic system project designed to support early
  warning and intervention workflows for students.
</p>

<h5 class="dg-legal-h" id="dg-legal-privacy-1">1) Personal data we collect</h5>
<ul class="mb-3">
  <li><strong>User account data</strong>: username, full name, role (Teacher/Counselor/Admin), email (optional), contact number (optional), account status, and password hash.</li>
  <li><strong>Student profile data</strong>: student name, grade level, strand (where applicable), section, LRN (optional), optional <strong>face photo</strong> path for identification, school-year batch assignments, overall GPA/absences/risk fields on the master record, and an <strong>archived</strong> flag when a profile is kept for history but excluded from active workflows.</li>
  <li><strong>Student performance and attendance</strong>: quarterly GPA/grades proxy, days present, total school days, absences, consecutive absences (and related fields stored in performance and grading tables).</li>
  <li><strong>Risk analytics</strong>: risk score/probability and risk level (Low/Moderate/High), including risk history generated by the ML component.</li>
  <li><strong>Intervention and case data</strong>: counselor notes, case status, teacher referrals, and issue flags (e.g., Health/Financial/Behavioral).</li>
  <li><strong>Security and audit data</strong>: login attempt records (username, IP, success flag, truncated user agent, timestamp), audit logs (action, status, target, description, optional JSON details, IP, user agent), and session identifiers stored server-side.</li>
</ul>

<h5 class="dg-legal-h" id="dg-legal-privacy-2">2) Sensitive personal information</h5>
<p class="mb-3">
  Drop Guard does not require sensitive personal information to function by default. However, some entries may
  become <em>sensitive personal information</em> depending on what is written in notes or flags (e.g., health-related
  concerns, financial hardship, family issues). Users should only encode what is necessary for legitimate student
  support purposes.
</p>

<h5 class="dg-legal-h" id="dg-legal-privacy-3">3) Why we collect data (legitimate purpose)</h5>
<ul class="mb-3">
  <li><strong>Account data</strong>: to authenticate users, assign role-based access, and secure the system.</li>
  <li><strong>Student and performance data</strong>: to identify at-risk students and support school-level monitoring.</li>
  <li><strong>Risk analytics</strong>: to generate early warning indicators and trends for decision support.</li>
  <li><strong>Interventions and referrals</strong>: to document actions taken and improve student support continuity.</li>
  <li><strong>Audit and security data</strong>: to detect misuse, investigate incidents, and maintain accountability.</li>
</ul>

<h5 class="dg-legal-h" id="dg-legal-privacy-4">4) How we use and process the data</h5>
<ul class="mb-3">
  <li>Data is encoded through the system UI and stored in a MySQL database.</li>
  <li>Risk scores and risk levels are generated using a Python-based ML module using performance/attendance inputs.</li>
  <li>Authorized users view dashboards, student profiles, and reports based on their <strong>role</strong> and, for teachers, <strong>assigned class visibility</strong> (students linked to the teacher in the system).</li>
  <li>Counselors and administrators typically have broader roster access consistent with school duties; exact rules follow your institution’s policy.</li>
  <li><strong>Archived</strong> student profiles remain stored but are excluded from active lists, dashboards, and many workflows until restored by authorized staff.</li>
  <li>Security logs are recorded for authentication attempts and significant actions.</li>
</ul>

<h5 class="dg-legal-h" id="dg-legal-privacy-5">5) Who controls the data (Personal Information Controller)</h5>
<p class="mb-3">
  For this academic project, the <strong>Personal Information Controller (PIC)</strong> is the system owner/operator
  (the school office/administrator in a real deployment; for class submission, the project team acts as the PIC for demonstration).
</p>

<h5 class="dg-legal-h" id="dg-legal-privacy-6">6) Data retention</h5>
<p class="mb-3">
  <strong>Policy intent (real deployments).</strong> Your institution may adopt retention rules such as: keeping user accounts while active
  (with deactivated accounts retained for accountability); keeping student academic/risk history for the active school year and a limited number of additional years for trend analysis;
  and keeping security/audit data for a bounded period for investigations. The periods in any school policy should be documented by your PIC/DPO.
</p>
<ul class="mb-3">
  <li><strong>Important—what the software does today:</strong> This build <strong>does not automatically delete or anonymize</strong> rows when a calendar retention period elapses.
  Audit logs, login-attempt records, and student data remain in the database until an administrator (or a future automated job defined by your institution) removes or archives them.
  Applying retention in production normally requires scheduled maintenance, backups, and legal review.</li>
  <li><strong>Student archiving</strong> is a <strong>soft</strong> status: records are hidden from routine operational views but not erased.</li>
  <li><strong>Account deactivation</strong> blocks sign-in; underlying user rows may remain for audit purposes unless your process deletes them.</li>
</ul>

<h5 class="dg-legal-h" id="dg-legal-privacy-7">7) Security measures (as implemented in this project)</h5>
<p class="mb-2">The following technical measures are part of the current codebase. They support—but do not replace—organizational policies, training, and infrastructure choices (e.g., HTTPS, database hardening, backups).</p>
<ul class="mb-3">
  <li><strong>Password security</strong>: passwords are verified with PHP’s <code>password_verify</code> against stored hashes (not plain text).</li>
  <li><strong>Session security</strong>: server-side session files; session cookie <strong>HttpOnly</strong> and <strong>SameSite=Lax</strong>; strict session mode; <strong>session ID regeneration</strong> on successful login; optional <strong>Secure</strong> cookie flag when the site is served over HTTPS.</li>
  <li><strong>Session timeout and binding</strong>: sessions end after a period of <strong>inactivity</strong> (implemented as roughly two hours without requests); the session is also tied to a browser fingerprint derived from the User-Agent to reduce simple session hijack—if the fingerprint no longer matches, the session is invalidated.</li>
  <li><strong>Access control</strong>: role-based restrictions on pages and actions (Teacher/Counselor/Admin), including teacher-scoped visibility where coded.</li>
  <li><strong>Brute-force protection</strong>: failed login attempts are recorded; repeated failures trigger <strong>temporary lockouts</strong> with progressive delay (per username/IP window).</li>
  <li><strong>CSRF mitigation</strong>: state-changing forms use server-issued <strong>CSRF tokens</strong> validated on POST.</li>
  <li><strong>Audit logging</strong>: many significant events (logins, logouts, data changes, denials, etc.) are written to an audit table with contextual metadata where implemented.</li>
  <li><strong>HTTP security headers</strong> (baseline): routed pages set headers such as <strong>X-Frame-Options: DENY</strong>, <strong>X-Content-Type-Options: nosniff</strong>, <strong>Referrer-Policy</strong>, and a restrictive <strong>Permissions-Policy</strong> for camera/microphone/geolocation.</li>
  <li><strong>Optional application-layer encryption</strong>: when a symmetric key is configured, selected <strong>text fields</strong> (for example parts of notes, audit descriptions, or JSON detail payloads) may be encrypted before storage using libsodium. <strong>Student names and LRN</strong> remain in plain form in the database in this design so search and uniqueness constraints work; institutions may add database or disk encryption separately.</li>
</ul>
<p class="text-muted small mb-0">
  Vulnerability management, penetration testing, SIEM, and DLP are <strong>not</strong> built into this academic project; plan them for production.
</p>

<h5 class="dg-legal-h" id="dg-legal-privacy-8">8) Your rights as a data subject</h5>
<p class="mb-2">Under the Data Privacy Act of 2012 (RA 10173), you have the following rights, subject to lawful limitations and institutional process:</p>
<ul class="mb-3">
  <li><strong>Right to be informed</strong>: know what data is collected and why.</li>
  <li><strong>Right to access</strong>: request access to your personal data stored in the system.</li>
  <li><strong>Right to correction</strong>: request correction of inaccurate or incomplete data.</li>
  <li><strong>Right to erasure or blocking</strong>: request deletion or blocking when allowed by law and when no longer necessary for legitimate purposes.</li>
  <li><strong>Right to data portability</strong>: request a copy of your data in a usable format when applicable.</li>
</ul>
<p class="mb-0 small">
  <strong>How this maps to the app:</strong> Staff users can update parts of their profile in the UI; broader requests (export, erasure, blocking) are expected to go through your
  <strong>school administrator or Data Protection Officer</strong>. The system does not currently provide a fully automated self-service portal for every data-subject right for every category of data.
</p>

<h5 class="dg-legal-h" id="dg-legal-privacy-9">9) How to contact us</h5>
<p class="mb-0">
  For privacy concerns, questions, or requests related to your data rights, contact the system owner/operator
  through your school administrator or the project team representative. If you are deploying this system in a real environment,
  provide an official email address and office contact details here.
</p>

<p class="dg-legal-footnote mt-4 mb-0">
  This notice is provided for transparency and privacy-by-design demonstration aligned with RA 10173. It is written to reflect the security and data practices implemented in this repository as accurately as possible; if the code changes, update this notice to match.
</p>
</div>
